### PR TITLE
Added two minor features

### PR DESCRIPTION
**Pull request by AliKHaliliT**
1. Fit method returns the history
2. Added callbacks parameter to the fit method

### CODE REVIEW

**Comment by Eillot29** [comment]
Hello,I'm trying to run the code and it worked.
But when I got the output from model. fit(), using history=model.fit()
this happens:
Traceback (most recent call last):
  File "D:/deep-tcn-tensorflow-main/example/example.py", line 72, in <module>
    print(history.history)
AttributeError: 'NoneType' object has no attribute 'history'

Do you have any ideas? Thanks！！！

**Comment by AliKHaliliT** [comment]
@Eillot29 
Hi,
The original author has not implemented the history object. I've added that in my fork. I am waiting for the original author to merge my pull request. After the merge, you can use that functionality.

**Comment by Eillot29** [comment]
@AliKHaliliT 
I understand.
Thanks for the quick response.

**Comment by flaviagiammarino** [comment]
[@Eillot29](https://github.com/Eillot29) please use [@AliKHaliliT](https://github.com/AliKHaliliT)'s fork: https://github.com/AliKHaliliT/deep-tcn-tensorflow.

**Comment by Eillot29** [comment]
Hi，

I would like to ask for advice.
When the encoder input contains one covariate, can the decoder of DeepTCN be described as M * two input residual blocks(resnet-v)? Each resnet-v outputs a predicted value for a future time step.


&nbsp;


沙尘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flaviagiammarino/deep-tcn-tensorflow] Added two minor features (PR #1)





 
@Eillot29
 Hi,
 The original author has not implemented the history object in the original repo. I've added that to my fork. I am waiting for the original author to merge my pull requests. After the merge, you can use that functionality.

**Pull request closed without merging**
